### ISSUE TITLE
Creating parity genesis block broken

### ISSUE THREAD

**Issue by Joool** [ethereum/evmlab#100]
Using the following script:
```python
import json
from evmlab import vm,genesis

geth = vm.ParityVM("parity_bin/parity-evm")
g = genesis.Genesis()
contract = "6000"
g.setConfigMetropolis()
(_, parity_g) = g.export()
g_out = geth.execute(code = contract, input="", genesis = parity_g, json=True, gas=1000000, memory=True)
```

Gives me the following error:  `Invalid --chain: Spec json is invalid: invalid value: integer `0`, expected a non-zero value at line 1 column 897`

Which corresponds to the "networkID" attribute of the genesis config. Thus changing `evmlab/genesis.py` line 103 to use network id 0x1, fixes the problem. However, I am unsure if this breaks anything?

**Comment by holiman** [comment]
It probably doesn't break anything important -- I usually use this with geth and not so much with parity. Strange though that I haven't encountered it. Please submit a PR to change it

**Comment by holiman** [comment]
Yeah, it's because they merged this: https://github.com/paritytech/parity-ethereum/pull/9763

**Comment by 5chdn** [comment]
Ouch.

**Comment by holiman** [comment]
Heh, yeah, hive too: https://github.com/karalabe/hive/commit/ae620fdc52140d24c18398ec137d0e8e9dd69410 . I'm pretty used to it :)
