### ISSUE TITLE
invalid opcode 0x1c

### ISSUE THREAD

**Issue by simonjaquilina** [ethereum/evmlab#125]
When using evmlab version installed using pip with docker image holiman/evmlab I was getting an "invalid opcode" when trying to trace a transaction containing the SHL, SHR or SAR opcodes. When trying the same with clone version from master I got empty trace file.

Following are the steps I followed to resolve the issue on the version cloned from master.

- Installed lates version of geth evm (1.9.9-stable-01744997) and start evmlab calling solution with "-g evm" and "--no-docker" flags. This will generate a trace file with the "invalid opcode" message in the trace file.
- To remove the "invalid opcode" message I had to change genesis.py "constantinopleBlock" value from "2000" to "0". This generated a complete json-trace but errors were still reported when generating the automated trace.
- To resolve issue with generation of automated trace file missing entry in evmtrace.py evmResult function npushes variable related to SHR opcode (0x1c = 28, this opcode consumes 2 entries from stack and push one back, therefore added entry "28 : 1" to npushes, the other entries are 27:1 and 29:1).
- A final change was done in reproducer.py related to the zip files functionality. Changed reference v[path] and v[name] to saved_files[v][path] and saved_files[v][name].

Putting this here in case it helps anyone else having same issue. 
I have also put the changes here:
https://github.com/sja785/evmlab/commit/7a9ae69f3362275da75c7c9a4155159a35a6a606

**Comment by holiman** [comment]
Thanks for investigating! The python-based evmlab is kind of deprecated, since I re-implemented it (most of it, at least), in go-lang: https://github.com/holiman/goevmlab

**Comment by simonjaquilina** [comment]
Thanks holiman, didn't know that. Will move to that one.
