### ISSUE TITLE
Get better Constantinople coverage when fuzzing

### ISSUE THREAD

**Issue by holiman** [ethereum/evmlab#71]
Ensure that we get more-than usual rate of the new Constantinople shift ops, `CREATE2` and `EXTCODEHASH` when the network/ruleset is `Constantinople`.

**Comment by tintinweb** [comment]
- [ ] add instructions to evm-instruction library that we are using. https://github.com/tintinweb/ethereum-dasm/pull/8.
- [ ] modify [codesmart.py](https://github.com/ethereum/evmlab/blob/master/evmlab/tools/statetests/rndval/codesmart.py) to create valid stack layout and mix in constantinople instructions more often.

**Comment by tintinweb** [comment]
https://github.com/ethereum/evmlab/tree/fix/zero_length_traces (does not hit 0 length traces that often - set a minimum balance and made sure gas is not easily exceeded. - interim solution)
