### ISSUE TITLE
speed up test generation

### ISSUE THREAD

**Issue by holiman** [ethereum/evmlab#80]
Invoking the random test generator takes about `21s` to generate `100` testcases. There must be ways to trim that?

**Comment by holiman** [comment]
If I make the codesmart module immedately return an empty block of code, I can generate `22670` testcases in `5s`

**Comment by tintinweb** [comment]
I'm working on this for the evmcodegen based generator which atm is even less performing (at least on my low resource vm). I am using cprofile get rid of the major time consumers and we'll see how much we can improve here.
