### ISSUE TITLE
Clean up after fuzzing

### ISSUE THREAD

**Issue by holiman** [ethereum/evmlab#90]
After 1.6M randomtests, the logs and testfiles eats up 281G on the disk. We need to make the fuzzer clean up after executions that did not result in any consensus failures. It can't be done via cron-job, since a cron-jon may delete a file that's just been written by the vm and hasn't been processed by evmlab yet.

**Comment by tintinweb** [comment]
I was about to add something that only preserves the consensus failures and removes logs/testfiles for 'good' executions. Afaik best place for this would be in code when we detect a consensus issue.

**Comment by holiman** [comment]
The preserving of consensus fails is already in place, but not the deletion

**Comment by holiman** [comment]
Heh, I see that I've already implemented this, just disabled it: https://github.com/ethereum/evmlab/blob/master/utilities/fuzzer.py#L125
